//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyLinhKienDienThoai.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SANPHAM
    {
        public int MASP { get; set; }
        public string TENSP { get; set; }
        public Nullable<decimal> GIA { get; set; }
        public string HINHANH { get; set; }
        public string THONGTIN { get; set; }
        public Nullable<int> SOLUONG { get; set; }
        public Nullable<int> MALOAISP { get; set; }
        public Nullable<int> MATHUONGHIEU { get; set; }
    
        public virtual LOAISANPHAM LOAISANPHAM { get; set; }
        public virtual THUONGHIEU THUONGHIEU { get; set; }
    }
}
