//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyLinhKienDienThoai.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class SANPHAM
    {
        [DisplayName(" Mã sản phẩm")]
        public int MASP { get; set; }
        [Required(ErrorMessage = "Tên sản phẩm bắt buộc nhập")]
        [DisplayName("Tên Sản Phẩm")]
        public string TENSP { get; set; }
        [DisplayName(" Đơn giá")]
        [DisplayFormat(DataFormatString = "{0:N0}", ApplyFormatInEditMode = true)]
        public Nullable<decimal> GIA { get; set; }
        [DisplayName(" hình ảnh")]
        [Required(ErrorMessage = "hình ảnh hiệu bắt buộc có")]
        public string HINHANH { get; set; }
        [DisplayName(" thông tin")]
        public string THONGTIN { get; set; }
        [Required(ErrorMessage = "số lượng hiệu bắt buộc nhập")]
        [StringLength(100,ErrorMessage ="Số lượng phải lớn hơn 0",MinimumLength =1)]
        [DisplayName(" Số lượng")]
        public Nullable<int> SOLUONG { get; set; }
        [DisplayName(" Mã Loại")]
        [Required(ErrorMessage = "mã loại hiệu bắt buộc có")]
        public Nullable<int> MALOAISP { get; set; }
        [DisplayName("Mã thương hiệu")]
        [Required(ErrorMessage = "thương  hiệu bắt buộc có")]
        public Nullable<int> MATHUONGHIEU { get; set; }
    
        public virtual LOAISANPHAM LOAISANPHAM { get; set; }
        public virtual THUONGHIEU THUONGHIEU { get; set; }
    }
}
